#!/bin/sh
set -x
PATH=$PATH:/usr/local/bin

[ -f "$0.rc" ] && . "$0.rc" || exit 1
[ -n "$PORTAGEHOST" -a -n "$TARGETDIR" ] || exit 1

umount /usr/portage || exit 1
rsync -avLPe ssh "$USER@$PORTAGEHOST:/mnt/gentoo/portage-current.sqfs" "$TARGETDIR"
mount /usr/portage
